#给一个对象注入属性
userinfo:
  age: 25
  name: wangxuwen
  active: true
  createDate: 2018/01/01 16:00:00
  map: {k1: a,k2: b}
  hobbies:
    - one
    - two
    - three

#tomcat 端口
server:
  port: 9090

#spring配置
spring:
  #配置自带的Jackson
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8

mysql:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=true
  username: root
  password: 123456

oracle:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/ORCL
  username: TEST
  password: wxw12345