#给一个对象注入属性
userinfo:
  age: 25
  name: wangxuwen
  active: true
  createDate: 2018/01/01 16:00:00
  map: {k1: a,k2: b}
  hobbies:
    - one
    - two
    - three

#tomcat 端口
server:
  port: 9090

#spring配置
spring:
  #配置自带的Jackson
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.249.128
    port: 5672
    username: test
    password: test
    virtual-host: /
  #redis配置
  redis:
    host: 192.168.249.128
    port: 6379
    password:
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 5000
    jedis.pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 50
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3000
      #连接池中的最大空闲连接
      max-idle: 20
      #连接池中的最小空闲连接
      min-idle: 2


mysql:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=true
  username: root
  password: 123456

oracle:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/ORCL
  username: TEST
  password: wxw12345

memcached:
  address: 192.168.249.128
  port: 11211
